"""Distributed asynchronous audio-transformation pipeline."""

from acheron.core.chunking import chunk_text
from acheron.core.errors import (
    AcheronError,
    CacheCorruptedError,
    CacheError,
    CacheMissError,
    ChunkingError,
    InvalidLanguagePathError,
    PlanError,
    PlanValidationError,
    WorkerError,
    WorkerTimeoutError,
    WorkerUnavailableError,
)
from acheron.core.interfaces import Executor, Worker
from acheron.core.models import (
    AudioRequest,
    Chunk,
    EpubRequest,
    ExecutorStrategy,
    Job,
    JobMetrics,
    JobRequest,
    JobResult,
    JobStatus,
    JsonValue,
    OutputFile,
    Plan,
    PlanResult,
    PlanStep,
    StepStatus,
    WorkerCapabilities,
    WorkerType,
)
from acheron.core.planner import compile_plan
from acheron.shell.executors import create_executor

__all__ = [
    "AcheronError",
    "AudioRequest",
    "CacheCorruptedError",
    "CacheError",
    "CacheMissError",
    "Chunk",
    "ChunkingError",
    "EpubRequest",
    "Executor",
    "ExecutorStrategy",
    "InvalidLanguagePathError",
    "Job",
    "JobMetrics",
    "JobRequest",
    "JobResult",
    "JobStatus",
    "JsonValue",
    "OutputFile",
    "Plan",
    "PlanError",
    "PlanResult",
    "PlanStep",
    "PlanValidationError",
    "StepStatus",
    "Worker",
    "WorkerCapabilities",
    "WorkerError",
    "WorkerTimeoutError",
    "WorkerType",
    "WorkerUnavailableError",
    "chunk_text",
    "compile_plan",
    "create_executor",
]
