# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: synthesis.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    "",
    "synthesis.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsynthesis.proto"Q\n\x10SynthesisRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t"r\n\x0bOutputChunk\x12\x12\n\x08pcm_data\x18\x01 \x01(\x0cH\x00\x12\x1d\n\x08\x61rtifact\x18\x02 \x01(\x0b\x32\t.ArtifactH\x00\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x42\t\n\x07payload"\x9c\x01\n\x08\x41rtifact\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12)\n\x08metadata\x18\x04 \x03(\x0b\x32\x17.Artifact.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"Y\n\x0f\x45xecuteResponse\x12\x1c\n\tartifacts\x18\x01 \x03(\x0b\x32\t.Artifact\x12\x19\n\x07metrics\x18\x02 \x01(\x0b\x32\x08.Metrics\x12\r\n\x05\x65rror\x18\x03 \x01(\t"\x8a\x01\n\x07Metrics\x12\x18\n\x10\x64uration_seconds\x18\x01 \x01(\x01\x12\x13\n\x0bgpu_seconds\x18\x02 \x01(\x01\x12\x11\n\ttokens_in\x18\x03 \x01(\x03\x12\x12\n\ntokens_out\x18\x04 \x01(\x03\x12\x15\n\rcost_estimate\x18\x05 \x01(\x01\x12\x12\n\ncost_basis\x18\x06 \x01(\t2<\n\tSynthesis\x12/\n\nSynthesize\x12\x11.SynthesisRequest\x1a\x0c.OutputChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "synthesis_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals["_ARTIFACT_METADATAENTRY"]._loaded_options = None
  _globals["_ARTIFACT_METADATAENTRY"]._serialized_options = b"8\001"
  _globals["_SYNTHESISREQUEST"]._serialized_start=19
  _globals["_SYNTHESISREQUEST"]._serialized_end=100
  _globals["_OUTPUTCHUNK"]._serialized_start=102
  _globals["_OUTPUTCHUNK"]._serialized_end=216
  _globals["_ARTIFACT"]._serialized_start=219
  _globals["_ARTIFACT"]._serialized_end=375
  _globals["_ARTIFACT_METADATAENTRY"]._serialized_start=328
  _globals["_ARTIFACT_METADATAENTRY"]._serialized_end=375
  _globals["_EXECUTERESPONSE"]._serialized_start=377
  _globals["_EXECUTERESPONSE"]._serialized_end=466
  _globals["_METRICS"]._serialized_start=469
  _globals["_METRICS"]._serialized_end=607
  _globals["_SYNTHESIS"]._serialized_start=609
  _globals["_SYNTHESIS"]._serialized_end=669
# @@protoc_insertion_point(module_scope)
